baseURL = 'https://jacobz.xyz/'
languageCode = 'en-us'
title = 'jacobz.xyz'
theme = 're-terminal' 

[params]
    # This theme allows for a subtitle and description
    subtitle = "artist"
    enableThemeSelection = false
    avatar = "/darklogo.png"
    logo = "/darklogo.png"
    contentTypeName = "posts"
    themeColor = "red"
    showMenuItems = 6
    showLanguageSelector = false
    fullWidthTheme = true
    centerTheme = true
    autoCover = true
    showLastUpdated = false
    scanlines = true
    terminalFont = true

[languages]
  [languages.en.params]
    languageName = "English"
    title = "re-Terminal"
    subtitle = "A simple, retro theme for Hugo"
    owner = ""
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"
    minuteReadingTime = "min read"
    words = "words"

    [languages.en.params.logo]
      logoText = "jacobz.xyz"
      logoHomeLink = "/"

    [languages.en.menu]
      # Submenus is available since v2.1.0
      # [[languages.en.menu.main]]
      #   identifier = "submenuParent"
      #   name = "Submenu"
      # [[languages.en.menu.main]]
      #   parent = "submenuParent"
      #   identifier = "anItem"
      #   name = "AnItem"
      [[languages.en.menu.main]]
        identifier = "categories"
        name = "categories"
        url = "/categories"
      [[languages.en.menu.main]]
        identifier = "tiktok"
        name = "tiktok"
        url = "https://www.tiktok.com/@jacobz.xyz"
      [[languages.en.menu.main]]
        identifier = "tags"
        name = "tags"
        url = "/tags"
