baseURL = 'https://jacobz.xyz/'
languageCode = 'en-us'
title = 'jacobz.xyz'
theme = 'diary'

[params]
    # This theme allows for a subtitle and description
    subtitle = "artist"
    enableThemeSelection = true
    logo = "darklogo.png"

[params.gitalk]
  owner = "user"
  repo = "repo name"

[build]
  writeStats = true

[imaging]
  resampleFilter = "Box"
  quality = 75

[[menu.main]]
url = "/categories"
name = "Categories"
weight = 3

[[menu.main]]
url = "/tags"
name = "Tags"
weight = 2

[[menu.main]]
url = "/posts"
name = "Archive"
weight = 1

[[menu.main]]
    name = "TikTok"
    url = "https://www.tiktok.com/@jacobz.xyz"
    weight = 2
