baseURL = 'https://jacobz.xyz/'
languageCode = 'en-us'
title = 'jacobz.xyz'
theme = 'diary'

[params]
    # This theme allows for a subtitle and description
    subtitle = "artist"
    enableThemeSelection = true
